# Generated by Django 5.1.7 on 2025-04-10 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventory',
            name='total_added',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
