# Generated by Django 5.1.7 on 2025-04-10 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_inventory_total_added'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventory',
            name='stock',
        ),
        migrations.RemoveField(
            model_name='inventory',
            name='total_added',
        ),
        migrations.AddField(
            model_name='inventory',
            name='total_stock_added',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
