# Generated by Django 5.1.7 on 2025-04-10 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_remove_inventory_stock_remove_inventory_total_added_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventory',
            name='stock',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
