# Generated by Django 5.1.7 on 2025-04-11 00:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_inventory_stock'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inventory',
            old_name='stock',
            new_name='quantity',
        ),
    ]
