# Generated by Django 5.2 on 2025-04-15 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("logistics", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="warehouse",
            name="capacity",
            field=models.IntegerField(default=0),
        ),
    ]
