# Generated by Django 5.2 on 2025-04-14 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vendors", "0002_warehouse"),
    ]

    operations = [
        migrations.AddField(
            model_name="inventory",
            name="total_stock_added",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
