# Generated by Django 5.2 on 2025-04-15 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="login_count",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
